# NumPy

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

In [1]:
import numpy as np

### NumPy Arrays

#### Creating NumPy Arrays:

In [2]:
#One dimensional array
x = np.array([1,2,3]) 
print(x)

[1 2 3]


In [3]:
#Multidimensional array
y = np.array([[1,2,3],[4,5,6],[7,8,9]]) 
print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
#Array with specific data type
z = np.array([1,2,3,4,5,6,7,8,9], dtype = int) 
print(z)

[1 2 3 4 5 6 7 8 9]


#### Initial Placeholders for Arrays:

In [5]:
#Creates a 2D array of zeros of shape 3×3
bln0 = np.zeros((3,3), dtype = int) 
print(bln0)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [6]:
#Creates a 2D array of zeros of shape 3×3
bln1 = np.ones((3,3), dtype = int) 
print(bln1)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [7]:
#Create an array of evenly spaced values (step value) 
step = np.arange(1,10,2, dtype = int) 
print(step)

[1 3 5 7 9]


In [8]:
#Create an array of evenly spaced values (number of samples)
samples = np.linspace(1,9,5, dtype = int) 
print(samples)

[1 3 5 7 9]


In [9]:
#Create a constant array of shape 3x3 full of 7
cons = np.full((3,3), 7) 
print(cons)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [10]:
#Create a 3X3 identity matrix
idm = np.eye(3, dtype = int) 
print(idm)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [11]:
#Create an array with random values
rand = np.random.random((3,3)) 
print(rand)

[[0.60221985 0.22216486 0.1438313 ]
 [0.7055726  0.76795979 0.87910969]
 [0.72713212 0.06854194 0.28031622]]


In [12]:
#Create an empty array of shape 3x3
empt = np.empty((3,3)) 

#### Data Types

Signed 64-bit integer types: <b>np.int64</b><br>
Standard double-precision floating point: <b>np.float32</b><br>
Complex numbers represented by 128 floats: <b>np.complex</b><br>
Boolean type storing TRUE and FALSE values: <b>np.bool</b><br>
Python object type: <b>np.object</b><br>
Fixed-length string type: <b>np.string_</b><br>
Fixed-length unicode type: <b>np.unicode_</b><br>

#### Inspecting Your Array

In [13]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [14]:
#Array dimensions
arr.shape 

(3, 3)

In [15]:
#Length of array 
len(arr) 

3

In [16]:
#Number of array dimensions 
arr.ndim 

2

In [17]:
#Number of array elements
arr.size 

9

In [18]:
#Data type of array elements
arr.dtype 

dtype('int32')

In [19]:
#Name of data type
arr.dtype.name 

'int32'

In [20]:
#Convert an array to a different type
arr.astype(float)

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

#### Array Mathematics

In [21]:
x = np.full((3,3), 10)
print(x)

[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [22]:
y = np.full((3,3), 2)
print(y)

[[2 2 2]
 [2 2 2]
 [2 2 2]]


In [23]:
#Addition
z = x + y
print(z)
#or
np.add(x,y)

[[12 12 12]
 [12 12 12]
 [12 12 12]]


array([[12, 12, 12],
       [12, 12, 12],
       [12, 12, 12]])

In [24]:
#Subtraction
z = x - y 
print(z)
#or
np.subtract(x,y)

[[8 8 8]
 [8 8 8]
 [8 8 8]]


array([[8, 8, 8],
       [8, 8, 8],
       [8, 8, 8]])

In [25]:
#Multiplication
z = x * y
print(z)
#or
np.multiply(x,y)

[[20 20 20]
 [20 20 20]
 [20 20 20]]


array([[20, 20, 20],
       [20, 20, 20],
       [20, 20, 20]])

In [26]:
#Division
z = x / y
print(z)
#or
np.divide(x,y)

[[5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]]


array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [27]:
#Exponentiation
np.exp(x)

array([[22026.46579481, 22026.46579481, 22026.46579481],
       [22026.46579481, 22026.46579481, 22026.46579481],
       [22026.46579481, 22026.46579481, 22026.46579481]])

In [28]:
#Square root
np.sqrt(x)

array([[3.16227766, 3.16227766, 3.16227766],
       [3.16227766, 3.16227766, 3.16227766],
       [3.16227766, 3.16227766, 3.16227766]])

In [29]:
#Sines
np.sin(x)

array([[-0.54402111, -0.54402111, -0.54402111],
       [-0.54402111, -0.54402111, -0.54402111],
       [-0.54402111, -0.54402111, -0.54402111]])

In [30]:
#Cosine
np.cos(x)

array([[-0.83907153, -0.83907153, -0.83907153],
       [-0.83907153, -0.83907153, -0.83907153],
       [-0.83907153, -0.83907153, -0.83907153]])

In [31]:
#Logarithm
np.log(x)

array([[2.30258509, 2.30258509, 2.30258509],
       [2.30258509, 2.30258509, 2.30258509],
       [2.30258509, 2.30258509, 2.30258509]])

In [32]:
#Dot product
np.dot(x,y)

array([[60, 60, 60],
       [60, 60, 60],
       [60, 60, 60]])

#### Comparison

In [33]:
x = np.array([1,2,3])
y = np.array([3,2,1])

In [34]:
x == y

array([False,  True, False])

In [35]:
x > y

array([False, False,  True])

#### Aggregate Functions

In [36]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [37]:
#Array-wise sum
arr.sum()

45

In [38]:
#Array-wise minimum value
arr.min()

1

In [39]:
#Maximum value of an array row
arr.max(axis=0)

array([7, 8, 9])

In [40]:
#Cumulative sum of the elements
arr.cumsum(axis=1)

array([[ 1,  3,  6],
       [ 4,  9, 15],
       [ 7, 15, 24]], dtype=int32)

In [41]:
#Mean
arr.mean()

5.0

In [42]:
#Median
np.median(arr)

5.0

In [43]:
#Correlation coefficient
np.corrcoef(arr)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [44]:
#Standard deviation
np.std(arr)

2.581988897471611

#### Copying Arrays

In [45]:
x = np.array([1,2,3])

In [46]:
#Create a view of the array with the same data
y = x.view()
print(y)

[1 2 3]


In [47]:
#Create a copy of the array
np.copy(x)

array([1, 2, 3])

In [48]:
#Create a deep copy of the array
y = x.copy()
print(y)

[1 2 3]


#### Sorting Arrays

In [49]:
arr = np.array([6,3,9,5,4,8,2,1,7])

In [50]:
arr.sort()
print(arr)

[1 2 3 4 5 6 7 8 9]


#### Subsetting

In [51]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [52]:
#Select the element at row 2 column 2 (equivalent to b[1][1])
arr[1,1]

5

#### Slicing

In [53]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [54]:
arr[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [55]:
arr[0:3,1]

array([2, 5, 8])

In [56]:
arr[:3]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [57]:
arr[::-1]

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

#### Transposing Array

In [58]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [59]:
arr.T
#or
arr.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

#### Changing Array Shape

In [60]:
arr = np.array([[1,2,3],[4,5,6]])

In [61]:
#Flatten the array
arr.ravel()

array([1, 2, 3, 4, 5, 6])

In [62]:
#Reshape, but don’t change data
arr.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

#### Adding/Removing Elements

In [63]:
arr = np.array([[1,2,3],[4,5,6]])

In [64]:
np.append(arr,[7,8,9])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
np.insert(arr,6,7)

array([1, 2, 3, 4, 5, 6, 7])

In [66]:
np.delete(arr,5)

array([1, 2, 3, 4, 5])